import React from "react";

const icons = {
  dashboard: <i className="fa-solid fa-chart-line"></i>,
  transactions: <i className="fa-solid fa-credit-card"></i>,
  categories: <i className="fa-solid fa-tags"></i>,
  accounts: <i className="fa-solid fa-wallet"></i>,
  settings: <i className="fa-solid fa-cog"></i>,
  logout: <i className="fa-solid fa-sign-out"></i>,
  trend: <i className="fa-solid fa-money-bill-trend-up"></i>,
  expenses: <i className="fa-solid fa-money-bill-transfer"></i>,
  money: <i className="fas fa-money-bill    "></i>,
  freelance: <i className="fas fa-book-reader"></i>,
  stocks: <i className="fa-solid fa-arrow-trend-up"></i>,
  bitcoin: <i className="fa fa-heart"></i>,
  piggy: <i className="fa-solid fa-piggy-bank"></i>,
  yt: <i className="fa-brands fa-youtube"></i>,
  card: <i className="fa-brands fa-cc-visa"></i>,
  users: <i className="fa-solid fa-users-between-lines"></i>,
  dollar: <i className="fas fa-rupee-sign"></i>,
  calender: <i className="fa-solid fa-calendar"></i>,
  comment: <i className="fa-solid fa-comment"></i>,
  plus: <i className="fa-solid fa-plus"></i>,
  trash: <i className="fa-solid fa-trash"></i>,
  signout: <i className="fa-solid fa-right-from-bracket"></i>,
  takeaway: <i className="fa-solid fa-utensils"></i>,
  clothing: <i className="fa-solid fa-shirt"></i>,
  book: <i className="fa-solid fa-book-open"></i>,
  food: <i className="fa-solid fa-bowl-food"></i>,
  medical: <i className="fa-solid fa-briefcase-medical"></i>,
  tv: <i className="fa-solid fa-tv"></i>,
  circle: <i className="fa-solid fa-circle-dot"></i>,
};

export default icons;
